#开发环境
#数据配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/code?characterEncoding=utf8&serverTimezone=UTC&useUnicode=true
    username: root
    password: 971223
  thymeleaf:
    cache: false #关闭缓存
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000ms
    jedis:
      pool:
        max-active: 8 #连接池最大连接数
        max-wait: -1ms #连接池最大阻塞等待的时间
        max-idle: 8 #连接池中的最大空闲链接
        min-idle: 0 #连接池中最小空闲链接

imgFilePath: D:/WithoutHair/imgforbishe/
lucenePath: D:/WithoutHair/lucene/